@startuml クラス図

title クラス図の例
left to right direction

class Enemy {
    name
    life_param
    attack_param
    special_param
    attack()
}

class Slime

class Wizard {
    magic()
}

Enemy <|-- Slime
Enemy <|-- Wizard

@enduml