@startuml シーケンス図
title シーケンス図の例

ユーザー -> ウェブブラウザ:「保存」ボタンクリック

ウェブブラウザ ->> HTTPサーバー:データの保存のリクエスト

HTTPサーバー -> ウェブアプリ:受信したデータの保存

ウェブアプリ -> ウェブアプリ:データの妥当性チェック
alt データが妥当である場合

ウェブアプリ -> データベース:データの保存処理
データベース --> ウェブアプリ:保存処理の結果
ウェブアプリ --> HTTPサーバー:保存処理の結果
else 

ウェブアプリ --> HTTPサーバー:保存処理の結果（失敗）
end

HTTPサーバー ->> ウェブブラウザ:保存処理の結果
ウェブブラウザ --> ユーザー:保存処理の結果を通知
@enduml