@startuml ユースケース図
title ユースケース図
' startuml ユースケース図： PlantUMLでユースケース図を描くことを宣言します。
' title ユースケース図： 図のタイトルを設定します。
!theme cyborg
left to right direction
' left to right direction： 図の要素を左から右に配置するように設定します。

skinparam actorStyle awesome
' skinparam actorStyle awesome の意味
'アクター（システムを利用する人）の表示スタイルを「かっこいい」に設定する という意味になります。

' 具体的に何が変わるのか？
' アクターの形状: シンプルな棒人間ではなく、より立体感や特徴のあるデザインになります。
' アクターの大きさ: 少し大きめになり、図の中で目立つようになります。
' アクターの表現力: 表情やポーズなど、より豊かな表現が可能になります。
actor 発注者
' actor 発注者： 発注者というアクター（システムを利用する人）を定義します。
actor ユーザー #pink
' actor ユーザー #pink： ユーザーというアクターを定義し、色をピンクに設定します。
skinparam Monochrome false
' skinparam Monochrome false の意味
' PlantUML で使われる skinparam Monochrome false は、図の見た目をカスタマイズするための設定の一つです。

' それぞれの単語の意味
' skinparam: スキンパラメータの略で、図のスタイルや見た目を設定するためのパラメータです。
' Monochrome: モノクローム、つまり単色という意味です。
' false: 偽、つまり「モノクロではない」という意味になります。
' この設定が意味すること
' skinparam Monochrome false と設定することで、図をモノクロではなく、カラーで表示するように指定します。つまり、図の中に様々な色を使うことができるようになります。

package "通販システム" #fafad2 {
' package "通販システム"： 通販システムというパッケージを定義し、背景色を設定します。
    usecase 商品を検索する #ffd700
    ' usecase 商品を検索する： 通販システムのユースケース「商品を検索する」を定義し、色を設定します。
    usecase 商品をカゴに入れる #ffd700
    usecase 購入手続きを行う #ffd700
    usecase 購入をキャンセルする #ffd700
    usecase 購入状況を確認する #ffd700
}

package "発注システム" #e0ffff {
    usecase 商品を発注する #a0e0f0
    usecase 発注をキャンセルする #a0e0f0
}

ユーザー --> 商品を検索する
' ユーザー --> 商品を検索する： ユーザーが「商品を検索する」というユースケースを利用することを表します。
ユーザー --> 商品をカゴに入れる
ユーザー --> 購入手続きを行う
ユーザー --> 購入をキャンセルする
購入状況を確認する <-- 発注者
発注者 --> 商品を発注する
発注者 --> 発注をキャンセルする

@enduml
